### ISSUE TITLE
Getting scaled data to plot with both banded contours and line contours

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/kale#13]
The [linked notebook](https://github.com/brendanjmeade/kale/blob/main/kale_log_example.ipynb) shows two plots.  The first is a classic linear plot with banded contours and thin black lines at the edges of the contours.  It looks great.  Below that plot is another where I have taken the base 10 log of the data.  The banded contour looks great but the black lines don't show up at the edges of contours. 

@banesullivan Can you take a look at this?

**Comment by banesullivan** [comment]
I think I may be missing some of the data files?

**Comment by brendanjmeade** [comment]
I think they all should be uploaded to our shared Google Drive folder.  Please let me know if there are any specific files still missing!

**Comment by banesullivan** [comment]
Just having some trouble download large files from Google Drive... we may need to find an alternative mechanism for sharing the larger files

**Comment by banesullivan** [comment]
It appears the VTK algorithm is struggling with the `-inf` values (and also `NaN`). Perfroming a slight modification of the inut values before the log operation seems to help (adding `0.0001` to avoid a `log(0)`):

```py
mesh.cell_data["data"] = np.log10(ds["cumulative_slip"][40000, :] + 0.0001)
```

Then, since the `CONTOUR_LEVELS` is a `logspace`, we need to set `log_scale=True,` in the `add_mesh()` arguments to make sure the `n_colors` are discretized in the log space so that the colors will align with the contour edges.
![screenshot (14)](https://user-images.githubusercontent.com/22067021/227994870-ffaa4a50-79e7-43bc-9d46-985fdd9ee46a.png)

**Comment by brendanjmeade** [comment]
@banesullivan Awesome!  Can you push these changes to the repo so that it's documented in code?

**Comment by banesullivan** [comment]
Should be good to go now
